# Generated by Django 5.2.17 on 2026-09-28 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        ('core', '0002_remove_parkingslot_is_occupied'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=20, max_digits=8)),
                ('min_charge', models.DecimalField(decimal_places=2, default=20, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('awaiting_payment', 'Awaiting Payment'), ('closed', 'Closed')], default='open', max_length=20)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='booking.booking')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.parkingslot')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.vehicle')),
            ],
        ),
    ]
