# Generated by Django 5.2.17 on 2026-09-28 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('slot_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('zone_name', models.CharField(max_length=20)),
                ('slot_type', models.CharField(choices=[('compact', 'Compact'), ('suv', 'SUV')], default='compact', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_occupied', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('plate', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(choices=[('compact', 'Compact'), ('suv', 'SUV')], default='compact', max_length=10)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
