# Generated by Django 5.2.17 on 2026-09-28 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingslot',
            name='is_occupied',
        ),
    ]
