# Generated by Django 6.1 on 2026-08-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('slot_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('zone_name', models.CharField(max_length=50)),
                ('slot_type', models.CharField(choices=[('Compact', 'Compact'), ('SUV', 'SUV')], default='Compact', max_length=10)),
                ('is_occupied', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('booked', 'Booked'), ('maintenance', 'Maintenance')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['slot_id'],
            },
        ),
    ]
