# Generated by Django 6.1 on 2026-08-14 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_no', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('owner_name', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_type', models.CharField(choices=[('Compact', 'Compact'), ('SUV', 'SUV')], default='Compact', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registered_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
